version: '3.8'

services:
  tissueproid-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4300:4300"
    environment:
      - NODE_ENV=production
      - PORT=4300
      # Add your environment variables here or use env_file
      # - DATABASE_URL=${DATABASE_URL}
      # - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      # - NEXTAUTH_URL=${NEXTAUTH_URL}
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    container_name: tissueproid-container
    networks:
      - tissueproid-network

networks:
  tissueproid-network:
    driver: bridge